/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _APP_H_RPCGEN
#define _APP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int a;
	int b;
};
typedef struct numbers numbers;

#define CALCUL_PROG 0x20000001
#define CALCUL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(numbers *, CLIENT *);
extern  int * add_1_svc(numbers *, struct svc_req *);
#define SUB 2
extern  int * sub_1(numbers *, CLIENT *);
extern  int * sub_1_svc(numbers *, struct svc_req *);
#define MUL 3
extern  int * mul_1(numbers *, CLIENT *);
extern  int * mul_1_svc(numbers *, struct svc_req *);
#define DIV 4
extern  float * div_1(numbers *, CLIENT *);
extern  float * div_1_svc(numbers *, struct svc_req *);
extern int calcul_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
#define SUB 2
extern  int * sub_1();
extern  int * sub_1_svc();
#define MUL 3
extern  int * mul_1();
extern  int * mul_1_svc();
#define DIV 4
extern  float * div_1();
extern  float * div_1_svc();
extern int calcul_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_APP_H_RPCGEN */
