/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"


void
calcul_prog_1(char *host, int a, int b)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  add_1_arg;
	int  *result_2;
	numbers  sub_1_arg;
	int  *result_3;
	numbers  mul_1_arg;
	float  *result_4;
	numbers  div_1_arg;

	add_1_arg.a = a; add_1_arg.b = b;
    sub_1_arg.a = a; sub_1_arg.b = b;
    mul_1_arg.a = a; mul_1_arg.b = b;
    div_1_arg.a = a; div_1_arg.b = b;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCUL_PROG, CALCUL_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = sub_1(&sub_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = mul_1(&mul_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = div_1(&div_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Result of addition: %d\n", *result_1);
	printf("Result of subtraction: %d\n", *result_2);
	printf("Result of multiplication: %d\n", *result_3);
	printf("Result of division: %f\n", *result_4);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
    int num1, num2;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
    num1 = atoi(argv[2]); 
    num2 = atoi(argv[3]);
	calcul_prog_1 (host,num1,num2);
exit (0);
}
